on:
  workflow_call:
    inputs:
      OR_VAR:
        type: string
        description: 'callee variable'
        required: false
        default: 'callee default value'


jobs:
  test-callee-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello ${{ inputs.OR_VAR }}"
